import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div>
            <Link href="/">Top</Link>
          </div>
          <div>
            <Link href="/blog">Blog</Link>
          </div>
          <div>
            <Link href="/blog/xxx">{`slug XXX`}</Link>
          </div>
          <div>
            <Link href="/dashboard">Dashboard</Link>
          </div>
          <div>
            <Link href="/dashboard/analytics">Analytics</Link>
          </div>
          <div>
            <Link href="/dashboard/settings">Settings</Link>
          </div>
          <div>
            <Link href="/dashboard/settings/password">Password</Link>
          </div>
          <div>
            <Link href="/dashboard/settings/profile">Profile</Link>
          </div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
